# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 破茧化蝶 # ex. I m Chuan
name: 冰蝶 # ex. icysuki
email: icysuiki@163.com
location: 广东·深圳 # ex. Nice, France
company: 我的公司
company_url: my_company_website
github_url: https://github.com/icysuki # ex. https://github.com/icysuki
github_username: icysuki # ex. icysuki
description: description_of_your_web_site
favicon: favicon.png # Image must be in assets/images
repository: github_username/github_username.github.io # ex. icysuki/icysuki.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://icysuki.github.io
url: http://www.icysuki.com

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: unpkg.com/embed-js@5.0.3/umd # ex. httpicysukigithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: 首页

  -
    href: /open-source
    label: 开源

  -
    href: /blog
    label: 文章

  -
    href: /archives
    label: 档案

  -
    href: /bookmark
    label: 书签

  -
    href: /about
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: icysuki
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: icysuki
    repo: blog-comments
    oauth:
        client_id: 9c0af59b83dfdc674629
        client_secret: 10e05898a467fe5f5b88b7a8303272a69c6078bd
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: icysuki
    repo: blog-comments
    clientID: 9c0af59b83dfdc674629
    clientSecret: 10e05898a467fe5f5b88b7a8303272a69c6078bd
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
